---
title: "Gov 50 Final Project"
author: "Allison Hunter"
description: "Educational Backgrounds of African American Students who Pursue Higher Educational Institutions in the US"
output:
  distill::distill_article:
    self_contained: false
---



## Project thoughts

I am interested in pursuing data related to African American (descendants of slaves) students in higher education institutions based on their high school (ie. public and private schools). I am intrigued based on the low representation from the Black demographic at institutions, especially Ivy Leagues like Harvard. Unfortunately, Harvard and a lot of institutions don't really collect that data of the ethnicity of Black students which is why I would like to come in and do the research needed to validate why we need to foster a sense of belonging for prospective and current students, bring more resources into schools who lack college prepatory and academic toolkits, and encourage African American students to apply.

## Research Question and Interest

My research question is "How does the attendance of public and private high schools, specifically in predominantly African American communities, impact the enrollment and representation of African American students in higher education institutions, including Ivy League schools like Harvard?" My hypothesis is that if you attend a private school (school that is well-resourced/college prep), you will be pipelined into more prestigious institutions in comparison to African American students who attend public schools. The explanatory variable of interest is the "Enrollment in Public or Private School." This variable can be measured by factors such as resources. For example, the number of Advanced Placement (AP) courses offered, the presence of college counseling programs, the availability of tutoring services, the availability of STEM programs, the availability of SAT/ACT prep courses, etc. Variation in this variable can be observed by comparing high schools in predominantly African American communities with differing levels of these resources which can give me data on whether or not the student went to private and public. The outcome variable of interest is the "Enrollment and Representation of African American Students in Higher Education Institutions." This can be measured by the percentage of African American students from different high schools who enroll in colleges or universities, particularly those at the Ivy League level, like Harvard. This variable can be observed through college enrollment data and demographic information. If the data analysis reveals that high schools in predominantly African American communities with greater availability of college preparatory resources and academic toolkits (aka private schools) exhibit a higher percentage of African American students enrolling in higher education institutions, including Ivy League schools like Harvard, this would support the hypothesis. Conversely, if the data analysis shows no significant correlation between the availability of college preparatory resources and academic toolkits in high schools and the enrollment of African American students in higher education institutions, or if the correlation is negative, this would disprove the hypothesis. It would indicate that factors other than resource availability may have a more substantial impact on the enrollment of African American students, and the hypothesis would not hold.






